import { useEffect } from "react";
import "@/styles/GlobalStyles.scss";
import Head from "next/head";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";
//Fonts https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
import localFont from "next/font/local";
import { Gabarito } from "next/font/google";

// How to import from GoogleFonts:
const gabarito = Gabarito({
  subsets: ["latin"],
  variable: "--font1", // This is the CSS variable name that will be used to reference the font, please use font1 for headings
});

// How to import from local:
const SofiaPro = localFont({
  src: "../../public/Fonts/sofiapro-light-webfont.woff2",
  weight: "400", // weights must be specified if not using a variable font
  subsets: ["latin"],
  formats: ["woff2"],
  variable: "--font2",
});

export default function App({ Component, pageProps }) {
  useEffect(() => {});

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=yes"
        />

        {/* 
        USE https://realfavicongenerator.net for favicon
        USE https://realfavicongenerator.net for favicon
        USE https://realfavicongenerator.net for favicon
        USE https://realfavicongenerator.net for favicon
         */}
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#000000" />
        <meta name="theme-color" content="#ffffff"></meta>
        {/* 
        USE https://metatags.io for meta tags
        USE https://metatags.io for meta tags
        USE https://metatags.io for meta tags
        USE https://metatags.io for meta tags 
        */}
      </Head>
      <main className={`${gabarito.variable} ${SofiaPro.variable}`}>
        <Header />
        <Component {...pageProps} />
        <Footer />
      </main>
    </>
  );
}
