import { useEffect, useState } from "react";
import "@/styles/GlobalStyles.scss";
import Head from "next/head";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";
//Fonts https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
import localFont from "next/font/local";
import { Gabarito, Poppins } from "next/font/google";
import dynamic from "next/dynamic";
const ParallaxProvider = dynamic(
  () => import("@/Components/ParallaxProvider"),
  { ssr: false }
);
// How to import from GoogleFonts:
const gabarito = Gabarito({
  subsets: ["latin"],
  variable: "--font1", // This is the CSS variable name that will be used to reference the font, please use font1 for headings
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "600", "700"],
  variable: "--font2", // This is the CSS variable name that will be used to reference the font, please use font1 for headings
});

const LemonMilk = localFont({
  src: [
    {
      path: "../../public/fonts/lemonmilk-bold-webfont.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/lemonmilk-light-webfont.woff2",
      weight: "300",
      style: "normal",
    },
  ],
  formats: ["woff2"],
  variable: "--font3",
});

export default function App({ Component, pageProps }) {
  const [hasAnimationPlayedOnce, sethasAnimationPlayedOnce] = useState(false);

  return (
    <>
      <Head>
        <title>VSS BOX</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=yes"
        />

        {/* 
        USE https://realfavicongenerator.net for favicon
        USE https://realfavicongenerator.net for favicon
        USE https://realfavicongenerator.net for favicon
        USE https://realfavicongenerator.net for favicon
         */}
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#000000" />
        <meta name="theme-color" content="#ffffff"></meta>
        <script
          defer
          type="module"
          src="https://unpkg.com/@splinetool/viewer@0.9.492/build/spline-viewer.js"
        ></script>
        {/* 
        USE https://metatags.io for meta tags
        USE https://metatags.io for meta tags
        USE https://metatags.io for meta tags
        USE https://metatags.io for meta tags 
        */}
      </Head>
      <main
        className={`${gabarito.variable} ${poppins.variable} ${LemonMilk.variable}`}
      >
        <Header />
        <ParallaxProvider>
          <Component
            {...pageProps}
            sethasAnimationPlayedOnce={sethasAnimationPlayedOnce}
            hasAnimationPlayedOnce={hasAnimationPlayedOnce}
          />
        </ParallaxProvider>

        {/* This is a preload div below, if its removed you end up seeing the footer first and get CLS */}
        <div
          id="preloaderDiv"
          style={{
            background: "#090516",
            height: "100vh",
            width: "100vw",
            display: hasAnimationPlayedOnce && "none",
          }}
        ></div>
        <Footer />
      </main>
    </>
  );
}
