import { useEffect, useState } from "react";
import "@/styles/GlobalStyles.scss";
import Head from "next/head";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";
//Fonts https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
import localFont from "next/font/local";
import { Gabarito, Poppins } from "next/font/google";
import dynamic from "next/dynamic";
import loader from "../../public/img/loader.svg";
import Image from "next/image";
import Script from "next/script";

const ParallaxProvider = dynamic(
  () => import("@/Components/ParallaxProvider"),
  { ssr: false }
);
// How to import from GoogleFonts:
const gabarito = Gabarito({
  subsets: ["latin"],
  variable: "--font1", // This is the CSS variable name that will be used to reference the font, please use font1 for headings
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "600", "700"],
  variable: "--font2", // This is the CSS variable name that will be used to reference the font, please use font1 for headings
});

const LemonMilk = localFont({
  src: [
    {
      path: "../../public/fonts/lemonmilk-bold-webfont.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/lemonmilk-light-webfont.woff2",
      weight: "300",
      style: "normal",
    },
  ],
  formats: ["woff2"],
  variable: "--font3",
});

export default function App({ Component, pageProps }) {
  const [hasAnimationPlayedOnce, sethasAnimationPlayedOnce] = useState(false);

  return (
    <>
      <Head>
        <title>VSS BOX</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=yes"
        />

        {/* 
        USE https://realfavicongenerator.net for favicon
        USE https://realfavicongenerator.net for favicon
        USE https://realfavicongenerator.net for favicon
        USE https://realfavicongenerator.net for favicon
         */}
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#090516" />
        <meta name="theme-color" content="#ffffff" />
        {/* 
        USE https://metatags.io for meta tags
        USE https://metatags.io for meta tags
        USE https://metatags.io for meta tags
        USE https://metatags.io for meta tags 
        */}

        {/* <!-- Primary Meta Tags --> */}
        <title>VSS-BOX</title>
        <meta name="title" content="VSS-BOX" />
        <meta
          name="description"
          content="No more basic templates or messy site builders! We craft beautiful custom websites tailored to your vision. From pixels to possibilities, we're here to provide beautiful and highly functional websites."
        />
        <meta property="og:site_name" content="VSS-BOX"></meta>
        {/* <!-- Open Graph / Facebook --> */}
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://vssbox.com/" />
        <meta property="og:title" content="VSS-BOX" />
        <meta
          property="og:description"
          content="No more basic templates or messy site builders! We craft beautiful custom websites tailored to your vision. From pixels to possibilities, we're here to provide beautiful and highly functional websites."
        />
        <meta
          property="og:image"
          content="https://strapi-images.sgp1.digitaloceanspaces.com/9e76ca27f86ee6be68943dc8874da5bb.jpg"
        />

        {/* <!-- Twitter --> */}
        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:url" content="https://vssbox.com/" />
        <meta property="twitter:title" content="VSS-BOX" />
        <meta
          property="twitter:description"
          content="No more basic templates or messy site builders! We craft beautiful custom websites tailored to your vision. From pixels to possibilities, we're here to provide beautiful and highly functional websites."
        />
        <meta
          property="twitter:image"
          content="https://strapi-images.sgp1.digitaloceanspaces.com/9e76ca27f86ee6be68943dc8874da5bb.jpg"
        />
      </Head>

      <main
        className={`${gabarito.variable} ${poppins.variable} ${LemonMilk.variable}`}
      >
        {/* 
        GOOGLE ANALYTICS
        GOOGLE ANALYTICS
        GOOGLE ANALYTICS
        GOOGLE ANALYTICS
        */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-C8X3MF9563"
          strategy="lazyOnload"
        />
        <Script id="google-analytics" strategy="lazyOnload">
          {`
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-C8X3MF9563');
        `}
        </Script>

        {/* 
          FACEBOOK PIXEL
          FACEBOOK PIXEL
          FACEBOOK PIXEL
          FACEBOOK PIXEL
        */}

        <Script id="facebook-analytics" strategy="lazyOnload">
          {`
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window, document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '1432716584341734');
fbq('track', 'PageView');
`}
        </Script>
        <noscript>
          <img
            height="1"
            width="1"
            style={{ display: "none" }}
            src="https://www.facebook.com/tr?id=1432716584341734&ev=PageView&noscript=1"
          />
        </noscript>

        <Header />
        <ParallaxProvider>
          <Component
            {...pageProps}
            sethasAnimationPlayedOnce={sethasAnimationPlayedOnce}
            hasAnimationPlayedOnce={hasAnimationPlayedOnce}
          />
        </ParallaxProvider>

        {/* This is a preload div below, if its removed you end up seeing the footer first and get CLS */}
        {process.env.NEXT_PUBLIC_INTRO_ANIMATION_ENABLED === "true" && (
          <div
            id="preloaderDiv"
            style={{
              background: "#090516",
              height: "100vh",
              width: "100vw",
              display: hasAnimationPlayedOnce ? "none" : "flex",
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            <Image src={loader} alt="Loader" className="preloader-animation" />
          </div>
        )}

        <Footer />
      </main>
    </>
  );
}
