/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 test4.glb --transform 
Files: test4.glb [99.6KB] > test4-transformed.glb [19.55KB] (80%)
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/test4-transformed.glb");
  const { actions } = useAnimations(animations, group);
  console.log(actions.move);
  useEffect(() => {
    actions.move.play();
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <pointLight
          name="Light"
          intensity={1351.413}
          decay={2}
          position={[4.076, 5.904, -1.005]}
          rotation={[-1.839, 0.602, 1.932]}
        />
        <group name="Suzanne" position={[0, 0, -21.952]}>
          <mesh
            name="Suzanne_1"
            geometry={nodes.Suzanne_1.geometry}
            material={materials.purple}
          />
          <mesh
            name="Suzanne_2"
            geometry={nodes.Suzanne_2.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            name="Suzanne_3"
            geometry={nodes.Suzanne_3.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            name="Suzanne_4"
            geometry={nodes.Suzanne_4.geometry}
            material={materials["Material.003"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/test4-transformed.glb");
