name: vssbox-pipeline.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Install and Build
        run: |
          npm install
          npm run build
          pm2 stop 1
          pm2 start 1
          pm2 save
          sudo service nginx restart
      - name: "Create env file"
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env.local
